ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('lanzamientos/', views.lanzamientos, name='lanzamientos'),
    path('sobre-mi/', views.sobremi, name='sobremi'),
    path('no-disponible/', views.nada, name='nada'),
    path('segunda-vista/', views.segunda_vista, name='segunda_vista'),
    path('fecha-actual/', views.fecha_actual, name='fecha_actual'),
    path('saludar/', views.saludar, name='saludar'),
    path('saludar/<str:nombre>/<str:apellido>/', views.bienvenida, name='bienvenida'),
    
    # CBV
    path('sugerencias/', views.ListarSugerencias.as_view(), name='listar_sugerencias'),
    path('sugerencias/crear/', views.CrearSugerencia.as_view(), name='crear_sugerencia'),
    path('sugerencias/eliminar/<int:pk>/', views.EliminarSugerencia.as_view(), name='eliminar_sugerencia'),
    path('sugerencias/modificar/<int:pk>/', views.ModificarSugerencia.as_view(), name='modificar_sugerencia'),
    path('sugerencias/<int:pk>/', views.MostrarSugerencia.as_view(), name='mostrar_sugerencia'),
]

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

inicio/models.py
from django.db import models

# Create your models here.

class Sugerencia(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    descripcion = models.TextField(null=True)
    
    def __str__(self):
        return f"Sugerencia: {self.nombre} - Edad: {self.edad}"

usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)

inicio/views.py
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from django.views.decorators.http import require_GET
from inicio.models import Sugerencia
from django.shortcuts import render, redirect
from inicio.form import CrearSugerenciaFormulario, BuscarSugerenciaFormulario, ModificarSugerenciaFormulario
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# v4
@login_required
def lanzamientos(request):
    # template = loader.get_template('inicio.html')
    
    segundos = datetime.now().second
    diccionario = {
        'mensaje': 'Este es el mensaje de inicio...',
        'segundos': segundos,
        'segundo_par': segundos%2 == 0,
        'segundo_redondo': segundos%10 == 0,
        'listado_de_numeros': list(range(25))
    }
    # renderizar_template = template.render(diccionario)
    # return HttpResponse(renderizar_template)
    return render(request, 'inicio/lanzamientos.html', diccionario)


@login_required
@require_GET
def sobremi(request):
    # template = loader.get_template('inicio.html')
    
    diccionario = {
    }
    return render(request, 'inicio/sobre_mi.html', diccionario)

@login_required
@require_GET
def nada(request):
    # template = loader.get_template('inicio.html')
    
    diccionario = {
    }
    return render(request, 'inicio/nada.html', diccionario)


    
def inicio(request):
    return render(request, 'inicio/inicio.html')

def segunda_vista(request):
    return HttpResponse('<h1>Soy la segunda vista!</h1>')

def fecha_actual(request):
    fecha = datetime.now()
    return HttpResponse(f'<h1>Fecha actual: {fecha}</h1>')

def saludar(request):
    return HttpResponse('Bienvenido/a!!!')

def bienvenida(request, nombre, apellido):
    return HttpResponse(f'Bienvenido/a {nombre.title()} {apellido.title()}!!!')



class CrearSugerencia(CreateView):
    model = Sugerencia
    template_name = 'inicio/CBV/crear_sugerencia_CBV.html'
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_sugerencias')
    
class ListarSugerencias(ListView):
    model = Sugerencia
    template_name = "inicio/CBV/listar_sugerencias_CBV.html"
    context_object_name = 'sugerencias'

class ModificarSugerencia(LoginRequiredMixin, UpdateView):
    model = Sugerencia
    template_name = "inicio/CBV/modificar_sugerencia_CBV.html"
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_sugerencias')
    
class EliminarSugerencia(LoginRequiredMixin, DeleteView):
    model = Sugerencia
    template_name = "inicio/CBV/eliminar_sugerencia_CBV.html"
    success_url = reverse_lazy('inicio:listar_sugerencias')
    
class MostrarSugerencia(DetailView):
    model = Sugerencia
    template_name = "inicio/CBV/mostrar_sugerencia_CBV.html"

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from usuario.form import MiFormularioDeCreacionDeUsuarios, MiFormularioDeEdicionDeDatosDeUsuario
from django.urls import reverse_lazy
from usuario.models import InfoExtra

# Create your views here.

def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'login.html',  {'formulario': formulario})
            
    formulario = AuthenticationForm()
    return render(request, 'login.html',  {'formulario': formulario})


def registrarse(request):
    
    if request.method == 'POST':
        formulario = MiFormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'registro.html', {'formulario': formulario})
            
    formulario = MiFormularioDeCreacionDeUsuarios()
    return render(request, 'registro.html', {'formulario': formulario})

@login_required
def edicion_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            
            formulario.save()
            return redirect('inicio:inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar}, instance=request.user)
        
    return render(request, 'edicion_perfil.html', {'formulario': formulario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'modificar_pass.html'
    success_url = reverse_lazy('usuario:editar_perfil')

inicio/templates/inicio/CBV/crear_sugerencia_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Crear Sugerencia
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:crear_sugerencia' %} method="POST">
    {% csrf_token %}
    <table>
        {{form}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_sugerencia_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar sugerencia
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:eliminar_sugerencia' sugerencia.id %} method="POST">
    {% csrf_token %}
    <p>Confirma el borrado de {{sugerencia}}</p>
    <button>Confirmar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/listar_sugerencias_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Listado de sugerencias
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href={% url 'inicio:crear_sugerencia' %}>Crear sugerencia</a>
</button>
{% comment %} <form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form> {% endcomment %}

{% if sugerencias %}
{% for sugerencia in sugerencias %}
<li>
    {{sugerencia}}
    <button>
        <a class="navbar-brand" href={% url 'inicio:mostrar_sugerencia' sugerencia.id %}>Ver mas</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'inicio:modificar_sugerencia' sugerencia.id %}>Modificar</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'inicio:eliminar_sugerencia' sugerencia.id %}>Eliminar</a>
    </button>
</li>
{% endfor %}
{% else %}
<p>No se encontraron datos cargados.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_sugerencia_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Modificar sugerencia
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:modificar_sugerencia' sugerencia.id %} method="POST">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_sugerencia_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencia</title>
{% endblock title_head %}

{% block h1_header %}
Sugerencia de {{sugerencia.nombre}}
{% endblock h1_header %}

{% block contenido %}
<li>Edad: {{sugerencia.edad}}</li>
<li>Descripcion: {{sugerencia.descripcion}}</li>
{% endblock contenido %}

inicio/templates/inicio/crear_sugerencia.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Crear una sugerencia
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Inicio
{% endblock h1_header %}

{% block contenido %}
<h1>Bienvenido a la página del DJ Facundo Noselli</h1>
<h3>El DJ y autor de varias canciones</h3>
<p>Acá encontrarás todo lo necesario para poder conocer todos sus lanzamientos, contactarlo para que musicalice tu fiesta y dejar tus sugerencias</p>
{% endblock contenido %}

inicio/templates/inicio/lanzamientos.html
{% extends 'base.html' %}

{% block title_head %}
<title>Lanzamientos</title>
{% endblock title_head %}

{% block h1_header %}
Últimos lanzamientos
{% endblock h1_header %}

{% block contenido %}
{% load static %}
<h3>Todos los lanzamientos de Facundo Noselli</h3>
<div style="background-color: #7df0ff; padding: 20px;">
    <img src="{% static '/static/assets/img/FINRemixes.jpg' %}" alt="" width="150" height="150" align="right">
    <h1>Primer Lanzamiento</h1>
    <h6>Musica de Cuarentena - Facundo Noselli</h6>
    <p>10/4/20</p>
    <button onclick="window.location.href='https://open.spotify.com/track/2Gq7Xne2KeW6kaEFFPCQvL?si=f7b39f6ccdec4468'">Reproducir</button>
</div>
<div style="background-color: #c885ff; padding: 20px;">
    <img src="{% static '/static/assets/img/recomenda.PNG' %}" alt="" width="150" height="150" align="right">
    <h1>Recomendado</h1>
    <h6>I feel it coming X Sin señal - Facundo Noselli</h6>
    <p>9/3/23</p>
    <button onclick="window.location.href='https://youtu.be/vXuCCOtuNDY'">Reproducir</button>
</div>
<ul class="list-inline mb-2">
    <li class="list-inline-item"><a href="{% url 'inicio:nada' %}">Ver más</a></li>
</ul>
{% endblock contenido %}

inicio/templates/inicio/listar_sugerencias.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencias</title>
{% endblock title_head %}

{% block h1_header %}
Listado de sugerencias
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href={% url 'inicio:crear_sugerencia' %}>Crear sugerencia</a>
</button>
<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>

{% if sugerencias %}
{% for sugerencia in sugerencias %}
<li>
    {{sugerencia}}
    <a href={% url 'inicio:eliminar_perro' sugerencia.id %}>Eliminar</a>
    <a href={% url 'inicio:modificar_sugerencia' sugerencia.id %}>Modificar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontraron datos cargados.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/modificar_sugerencia.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sugerencia</title>
{% endblock title_head %}

{% block h1_header %}
Modificar sugerencias
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/nada.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sobre mi</title>
{% endblock title_head %}

{% block h1_header %}
No disponible
{% endblock h1_header %}

{% block contenido %}
<h3>No hay más páginas por el momento, vuelva más tarde</h3>
{% endblock contenido %}

inicio/templates/inicio/sobre_mi.html
{% extends 'base.html' %}

{% block title_head %}
<title>Sobre mi</title>
{% endblock title_head %}

{% block h1_header %}
Acerca de mi
{% endblock h1_header %}

{% block contenido %}
<h1>Algo de mi historia</h1>
<br>
<h3>Mis inicios</h3>
<p>Naci el 15 de octubre de 2004 en la Ciudad de Buenos Aires, en Argentina. Crecí en el hermoso barrio de Boedo donde supe encontrar una ecelente comunidad. Allí pude desarrollar mis estudios de nivel inicial y medio.
    Desde que tenia 13 años, empece a mostrar una gran atraccion hacia la Musica, tecnologia, la programacion, los DJ, autores de canciones, entre otros. Fue asi que decidi empezar mi propio camino.
    Empece escuchando algunos DJ famosos como Alan Walker, Kygo y sobre todo mi favorito: Avicii. Tambien desarrollé un gran gusto por la música de los 80 & 90, empezado así a realizar mis creaciones de combinación entre música antigua con la más reciente.</p>
<br>
<h3>Actualidad</h3>
<p>Como DJ, mi trabajo consiste en crear una experiencia musical que conecte con el público y los haga disfrutar al máximo. Para ello, selecciono cuidadosamente la música que se adapte al ambiente y a las preferencias de la audiencia, ya sea en un festival, boliche o una fiesta privada. Además, utilizo mi habilidad en la mezcla y la técnica para crear transiciones suaves y fluidas entre las canciones, manteniendo siempre el ritmo y la energía en alto.</p>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static '/static/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:lanzamientos' %}>Lanzamientos</a>
                <a class="navbar-brand" href={% url 'inicio:listar_sugerencias' %}>Sugerencias</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <img src={{request.user.infoextra.avatar.url}} alt="" height='40px'>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>

        {% block header %}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                La web del DJ Facundo Noselli
                                {% endblock h1_header %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}

        {% block contenido %}
        <p>Página base</p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'inicio:sobremi' %}">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="https://mail.google.com/mail/u/0/#inbox?compose=CllgCJlLXFFNRCLggnfBvHLzVvgGZcMFmSbZjJzzMQXwFrHBQpRvdnzGTdpKqMQTBGswzRFNGzL">Contact</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Página web del DJ Facundo Noselli. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href={% url 'inicio:nada' %}><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="https://twitter.com/Facu_Noselli"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/facu_noselli/"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

usuario/templates/edicion_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Edicion perfil</title>
{% endblock title_head %}

{% block h1_header %}
Editar perfil
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contrasenia</a></button>
</form>
{% endblock contenido %}

usuario/templates/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Login</button>
</form>
{% endblock contenido %}

usuario/templates/logout.html
{% extends 'base.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
Te deslogueaste con exito!
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuario/templates/modificar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar pass</title>
{% endblock title_head %}

{% block h1_header %}
Modificar pass
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

usuario/templates/registro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrar</button>
</form>
{% endblock contenido %}